

def generate_additional_interactions():
    """Additional drug interactions to reach 350+"""
    additional_interactions = {
        "critical": [
            # DOAC interactions
            {"drug_1": "利伐沙班", "drug_2": "酮康唑", "severity": "critical", "effect": "出血风险增加", "mechanism": "CYP3A4/P-gp抑制", "management": "避免联用"},
            {"drug_1": "阿哌沙班", "drug_2": "克拉霉素", "severity": "critical", "effect": "出血风险增加", "mechanism": "CYP3A4/P-gp抑制", "management": "避免联用"},
            {"drug_1": "达比加群", "drug_2": "决奈达隆", "severity": "critical", "effect": "出血风险增加", "mechanism": "P-gp抑制", "management": "避免联用"},
            {"drug_1": "依度沙班", "drug_2": "利福平", "severity": "critical", "effect": "疗效降低", "mechanism": "CYP3A4诱导", "management": "避免联用"},

            # Antiplatelet interactions
            {"drug_1": "普拉格雷", "drug_2": "阿司匹林", "severity": "critical", "effect": "出血风险增加", "mechanism": "协同抗血小板", "management": "谨慎联用"},
            {"drug_1": "替格瑞洛", "drug_2": "阿司匹林", "severity": "critical", "effect": "出血风险增加", "mechanism": "协同抗血小板", "management": "监测出血"},
            {"drug_1": "双嘧达莫", "drug_2": "华法林", "severity": "critical", "effect": "出血风险增加", "mechanism": "协同抗凝", "management": "监测INR"},
        ],
        "moderate": [
            # Antibiotic + various
            {"drug_1": "左氧氟沙星", "drug_2": "格列本脲", "severity": "moderate", "effect": "低血糖", "mechanism": "不确定", "management": "监测血糖"},
            {"drug_1": "莫西沙星", "drug_2": "格列美脲", "severity": "moderate", "effect": "低血糖", "mechanism": "不确定", "management": "监测血糖"},
            {"drug_1": "多西环素", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度升高", "mechanism": "代谢抑制", "management": "监测环孢素浓度"},
            {"drug_1": "米诺环素", "drug_2": "维A酸类", "severity": "moderate", "effect": "颅内压升高", "mechanism": "协同效应", "management": "避免联用"},

            # Antifungal + various
            {"drug_1": "氟康唑", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度升高", "mechanism": "CYP3A4抑制", "management": "监测环孢素"},
            {"drug_1": "伊曲康唑", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度升高", "mechanism": "CYP3A4抑制", "management": "监测环孢素"},
            {"drug_1": "伏立康唑", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度升高", "mechanism": "CYP3A4抑制", "management": "减量并监测"},
            {"drug_1": "两性霉素B", "drug_2": "地高辛", "severity": "moderate", "effect": "地高辛毒性", "mechanism": "肾损害", "management": "监测地高辛和肾功能"},
            {"drug_1": "氟康唑", "drug_2": "苯妥英钠", "severity": "moderate", "effect": "苯妥英浓度升高", "mechanism": "CYP抑制", "management": "监测苯妥英"},
            {"drug_1": "氟康唑", "drug_2": "利福平", "severity": "moderate", "effect": "氟康唑浓度降低", "mechanism": "CYP诱导", "management": "增加氟康唑剂量"},
            {"drug_1": "伊曲康唑", "drug_2": "利福平", "severity": "moderate", "effect": "伊曲康唑浓度降低", "mechanism": "CYP3A4诱导", "management": "避免联用"},
            {"drug_1": "伏立康唑", "drug_2": "利福平", "severity": "moderate", "effect": "伏立康唑浓度降低", "mechanism": "CYP3A4诱导", "management": "避免联用"},

            # Antiviral + various
            {"drug_1": "利托那韦", "drug_2": "阿托伐他汀", "severity": "moderate", "effect": "肌病风险增加", "mechanism": "CYP3A4抑制", "management": "限制他汀剂量"},
            {"drug_1": "利托那韦", "drug_2": "辛伐他汀", "severity": "critical", "effect": "肌病、横纹肌溶解", "mechanism": "CYP3A4抑制", "management": "禁用辛伐他汀"},
            {"drug_1": "利托那韦", "drug_2": "华法林", "severity": "moderate", "effect": "INR变化", "mechanism": "CYP诱导/抑制复杂", "management": "密切监测INR"},
            {"drug_1": "阿昔洛韦", "drug_2": "替诺福韦", "severity": "moderate", "effect": "肾毒性增加", "mechanism": "协同肾毒性", "management": "监测肾功能"},
            {"drug_1": "更昔洛韦", "drug_2": "缬更昔洛韦", "severity": "moderate", "effect": "骨髓抑制加重", "mechanism": "协同骨髓抑制", "management": "监测血象"},

            # Cardiovascular additional
            {"drug_1": "地尔硫卓", "drug_2": "辛伐他汀", "severity": "moderate", "effect": "肌病风险增加", "mechanism": "CYP3A4抑制", "management": "辛伐他汀≤20mg"},
            {"drug_1": "地尔硫卓", "drug_2": "阿托伐他汀", "severity": "moderate", "effect": "肌病风险增加", "mechanism": "CYP3A4抑制", "management": "监测CK"},
            {"drug_1": "维拉帕米", "drug_2": "辛伐他汀", "severity": "moderate", "effect": "肌病风险增加", "mechanism": "CYP3A4抑制", "management": "辛伐他汀≤20mg"},
            {"drug_1": "维拉帕米", "drug_2": "阿托伐他汀", "severity": "moderate", "effect": "肌病风险增加", "mechanism": "CYP3A4抑制", "management": "监测CK"},
            {"drug_1": "胺碘酮", "drug_2": "普伐他汀", "severity": "moderate", "effect": "肌病风险", "mechanism": "相互作用", "management": "监测CK"},
            {"drug_1": "胺碘酮", "drug_2": "氟西汀", "severity": "moderate", "effect": "QT延长", "mechanism": "协同QT延长", "management": "监测心电图"},
            {"drug_1": "胺碘酮", "drug_2": "帕罗西汀", "severity": "moderate", "effect": "QT延长", "mechanism": "协同QT延长", "management": "监测心电图"},
            {"drug_1": "索他洛尔", "drug_2": "西酞普兰", "severity": "moderate", "effect": "QT延长", "mechanism": "协同QT延长", "management": "监测心电图"},
            {"drug_1": "普罗帕酮", "drug_2": "氟西汀", "severity": "moderate", "effect": "普罗帕酮浓度升高", "mechanism": "CYP2D6抑制", "management": "监测药物浓度"},
            {"drug_1": "奎尼丁", "drug_2": "酮康唑", "severity": "moderate", "effect": "QT延长", "mechanism": "CYP3A4抑制", "management": "避免联用"},
            {"drug_1": "奎尼丁", "drug_2": "胺碘酮", "severity": "moderate", "effect": "QT延长", "mechanism": "协同QT延长", "management": "避免联用"},
            {"drug_1": "多非利特", "drug_2": "维拉帕米", "severity": "moderate", "effect": "QT延长", "mechanism": "协同QT延长", "management": "避免联用"},
            {"drug_1": "伊布利特", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "QT延长", "mechanism": "协同QT延长", "management": "监测心电图"},

            # Diabetes + cardiovascular
            {"drug_1": "二甲双胍", "drug_2": "呋塞米", "severity": "moderate", "effect": "二甲双胍蓄积", "mechanism": "肾功能影响", "management": "监测肾功能"},
            {"drug_1": "格列吡嗪", "drug_2": "氟康唑", "severity": "moderate", "effect": "低血糖", "mechanism": "代谢抑制", "management": "监测血糖"},
            {"drug_1": "格列美脲", "drug_2": "氟康唑", "severity": "moderate", "effect": "低血糖", "mechanism": "代谢抑制", "management": "监测血糖"},
            {"drug_1": "那格列奈", "drug_2": "吉非贝齐", "severity": "moderate", "effect": "那格列奈浓度升高", "mechanism": "OATP抑制", "management": "监测血糖"},
            {"drug_1": "瑞格列奈", "drug_2": "吉非贝齐", "severity": "moderate", "effect": "瑞格列奈浓度升高", "mechanism": "代谢抑制", "management": "监测血糖"},
            {"drug_1": "吡格列酮", "drug_2": "阿托伐他汀", "severity": "moderate", "effect": "两者浓度升高", "mechanism": "相互竞争", "management": "监测不良反应"},
            {"drug_1": "罗格列酮", "drug_2": "吉非贝齐", "severity": "moderate", "effect": "罗格列酮浓度升高", "mechanism": "代谢抑制", "management": "监测血糖"},
            {"drug_1": "西格列汀", "drug_2": "环孢素", "severity": "moderate", "effect": "西格列汀浓度轻度升高", "mechanism": "p-gp抑制", "management": "监测血糖"},
            {"drug_1": "沙格列汀", "drug_2": "酮康唑", "severity": "moderate", "effect": "沙格列汀浓度升高", "mechanism": "CYP3A4抑制", "management": "沙格列汀限制剂量"},

            # Antihistamine interactions
            {"drug_1": "氯雷他定", "drug_2": "酮康唑", "severity": "moderate", "effect": "氯雷他定浓度升高", "mechanism": "CYP3A4抑制", "management": "限制剂量"},
            {"drug_1": "氯雷他定", "drug_2": "大环内酯类", "severity": "moderate", "effect": "氯雷他定浓度升高", "mechanism": "CYP3A4抑制", "management": "监测不良反应"},
            {"drug_1": "西替利嗪", "drug_2": "茶碱", "severity": "moderate", "effect": "镇静作用增强", "mechanism": "未知", "management": "谨慎驾驶"},
            {"drug_1": "非索非那定", "drug_2": "酮康唑", "severity": "moderate", "effect": "非索非那定浓度升高", "mechanism": "OATP抑制", "management": "一般无需调整"},

            # Respiratory + cardiovascular
            {"drug_1": "沙丁胺醇", "drug_2": "利尿剂", "severity": "moderate", "effect": "低钾血症", "mechanism": "协同降钾", "management": "监测血钾"},
            {"drug_1": "沙美特罗", "drug_2": "β阻滞剂", "severity": "moderate", "effect": "沙美特罗疗效降低", "mechanism": "β受体拮抗", "management": "避免使用非选择性β阻滞剂"},
            {"drug_1": "福莫特罗", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "福莫特罗疗效降低", "mechanism": "β受体拮抗", "management": "避免联用"},
            {"drug_1": "氨茶碱", "drug_2": "西咪替丁", "severity": "moderate", "effect": "茶碱中毒", "mechanism": "CYP抑制", "management": "监测茶碱浓度"},
            {"drug_1": "氨茶碱", "drug_2": "环丙沙星", "severity": "moderate", "effect": "茶碱中毒", "mechanism": "CYP1A2抑制", "management": "监测茶碱浓度"},
            {"drug_1": "氨茶碱", "drug_2": "红霉素", "severity": "moderate", "effect": "茶碱中毒", "mechanism": "CYP3A4抑制", "management": "监测茶碱浓度"},
            {"drug_1": "氨茶碱", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "支气管痉挛", "mechanism": "β受体阻滞", "management": "避免联用"},
            {"drug_1": "多索茶碱", "drug_2": "左氧氟沙星", "severity": "moderate", "effect": "茶碱浓度可能升高", "mechanism": "代谢抑制", "management": "监测茶碱浓度"},

            # CNS drug interactions
            {"drug_1": "地西泮", "drug_2": "西咪替丁", "severity": "moderate", "effect": "地西泮作用增强", "mechanism": "代谢抑制", "management": "减少地西泮剂量"},
            {"drug_1": "地西泮", "drug_2": "茶碱", "severity": "moderate", "effect": "相互药效降低", "mechanism": "复杂相互作用", "management": "调整剂量"},
            {"drug_1": "劳拉西泮", "drug_2": "丙戊酸钠", "severity": "moderate", "effect": "劳拉西泮浓度升高", "mechanism": "葡萄糖醛酸化抑制", "management": "监测镇静作用"},
            {"drug_1": "氯硝西泮", "drug_2": "丙戊酸钠", "severity": "moderate", "effect": "氯硝西泮浓度升高", "mechanism": "代谢抑制", "management": "监测镇静作用"},
            {"drug_1": "阿普唑仑", "drug_2": "氟西汀", "severity": "moderate", "effect": "阿普唑仑浓度升高", "mechanism": "CYP3A4抑制", "management": "减少阿普唑仑剂量"},
            {"drug_1": "阿普唑仑", "drug_2": "西咪替丁", "severity": "moderate", "effect": "阿普唑仑作用增强", "mechanism": "CYP3A4抑制", "management": "减少剂量"},
            {"drug_1": "咪达唑仑", "drug_2": "酮康唑", "severity": "critical", "effect": "咪达唑仑作用增强延长", "mechanism": "CYP3A4抑制", "management": "减量50%"},
            {"drug_1": "咪达唑仑", "drug_2": "克拉霉素", "severity": "critical", "effect": "咪达唑仑作用增强", "mechanism": "CYP3A4抑制", "management": "减量并延长观察"},
            {"drug_1": "唑吡坦", "drug_2": "酮康唑", "severity": "moderate", "effect": "唑吡坦作用增强", "mechanism": "CYP3A4抑制", "management": "减少剂量"},
            {"drug_1": "佐匹克隆", "drug_2": "红霉素", "severity": "moderate", "effect": "佐匹克隆浓度升高", "mechanism": "CYP3A4抑制", "management": "减少剂量"},
            {"drug_1": "右佐匹克隆", "drug_2": "酮康唑", "severity": "moderate", "effect": "右佐匹克隆浓度升高", "mechanism": "CYP3A4抑制", "management": "减少剂量"},
            {"drug_1": "氟西汀", "drug_2": "曲马多", "severity": "moderate", "effect": "5-羟色胺综合征风险", "mechanism": "5-HT蓄积", "management": "谨慎联用"},
            {"drug_1": "氟西汀", "drug_2": "曲马多", "drug_3": "MAOI", "severity": "critical", "effect": "5-羟色胺综合征", "mechanism": "5-HT蓄积", "management": "禁用"},
            {"drug_1": "氟西汀", "drug_2": "卡马西平", "severity": "moderate", "effect": "相互浓度降低", "mechanism": "酶诱导/抑制", "management": "监测药物浓度"},
            {"drug_1": "帕罗西汀", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "普萘洛尔浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心率和血压"},
            {"drug_1": "帕罗西汀", "drug_2": "美托洛尔", "severity": "moderate", "effect": "美托洛尔浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心率血压"},
            {"drug_1": "帕罗西汀", "drug_2": "恩卡尼", "severity": "moderate", "effect": "恩卡尼浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心电图"},
            {"drug_1": "帕罗西汀", "drug_2": "氟卡尼", "severity": "moderate", "effect": "氟卡尼浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心电图"},
            {"drug_1": "舍曲林", "drug_2": "华法林", "severity": "moderate", "effect": "INR升高", "mechanism": "蛋白结合置换", "management": "监测INR"},
            {"drug_1": "舍曲林", "drug_2": "匹莫齐特", "severity": "moderate", "effect": "匹莫齐特浓度升高", "mechanism": "CYP2D6抑制", "management": "避免联用"},
            {"drug_1": "西酞普兰", "drug_2": "美托洛尔", "severity": "moderate", "effect": "美托洛尔浓度轻度升高", "mechanism": "CYP2D6抑制", "management": "监测心率"},
            {"drug_1": "艾司西酞普兰", "drug_2": "美托洛尔", "severity": "moderate", "effect": "美托洛尔浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心率"},
            {"drug_1": "文拉法辛", "drug_2": "美托洛尔", "severity": "moderate", "effect": "美托洛尔浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心率血压"},
            {"drug_1": "度洛西汀", "drug_2": "卡马西平", "severity": "moderate", "effect": "度洛西汀浓度降低", "mechanism": "CYP1A2诱导", "management": "增加度洛西汀剂量"},
            {"drug_1": "安非他酮", "drug_2": "美托洛尔", "severity": "moderate", "effect": "美托洛尔浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心率血压"},
            {"drug_1": "安非他酮", "drug_2": "左旋多巴", "severity": "moderate", "effect": "左旋多巴疗效降低", "mechanism": "多巴胺拮抗", "management": "调整左旋多巴剂量"},
            {"drug_1": "米氮平", "drug_2": "地西泮", "severity": "moderate", "effect": "中枢抑制加重", "mechanism": "协同镇静", "management": "谨慎驾驶"},
            {"drug_1": "曲唑酮", "drug_2": "地高辛", "severity": "moderate", "effect": "地高辛浓度升高", "mechanism": "P-gp抑制", "management": "监测地高辛"},
            {"drug_1": "奈法唑酮", "drug_2": "阿普唑仑", "severity": "moderate", "effect": "阿普唑仑浓度升高", "mechanism": "CYP3A4抑制", "management": "减少剂量"},
            {"drug_1": "马普替林", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "相互浓度升高", "mechanism": "代谢抑制", "management": "监测不良反应"},
            {"drug_1": "奥氮平", "drug_2": "氟西汀", "severity": "moderate", "effect": "奥氮平浓度升高", "mechanism": "CYP1A2抑制", "management": "监测不良反应"},
            {"drug_1": "奥氮平", "drug_2": "卡马西平", "severity": "moderate", "effect": "奥氮平浓度降低", "mechanism": "CYP1A2诱导", "management": "增加奥氮平剂量"},
            {"drug_1": "利培酮", "drug_2": "帕罗西汀", "severity": "moderate", "effect": "利培酮浓度升高", "mechanism": "CYP2D6抑制", "management": "监测不良反应"},
            {"drug_1": "利培酮", "drug_2": "氟西汀", "severity": "moderate", "effect": "利培酮浓度升高", "mechanism": "CYP2D6抑制", "management": "监测不良反应"},
            {"drug_1": "喹硫平", "drug_2": "红霉素", "severity": "moderate", "effect": "喹硫平浓度升高", "mechanism": "CYP3A4抑制", "management": "监测不良反应"},
            {"drug_1": "喹硫平", "drug_2": "酮康唑", "severity": "moderate", "effect": "喹硫平浓度升高", "mechanism": "CYP3A4抑制", "management": "减量并监测"},
            {"drug_1": "阿立哌唑", "drug_2": "卡马西平", "severity": "moderate", "effect": "阿立哌唑浓度降低", "mechanism": "CYP3A4诱导", "management": "增加阿立哌唑剂量"},
            {"drug_1": "齐拉西酮", "drug_2": "卡马西平", "severity": "moderate", "effect": "齐拉西酮浓度降低", "mechanism": "CYP3A4诱导", "management": "增加剂量"},
            {"drug_1": "氯丙嗪", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "两者浓度均升高", "mechanism": "相互抑制代谢", "management": "监测不良反应"},
            {"drug_1": "氟哌啶醇", "drug_2": "卡马西平", "severity": "moderate", "effect": "氟哌啶醇浓度降低", "mechanism": "酶诱导", "management": "增加剂量"},
            {"drug_1": "锂剂", "drug_2": "氢氯噻嗪", "severity": "moderate", "effect": "锂中毒", "mechanism": "肾小管重吸收增加", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "ACE抑制剂", "severity": "moderate", "effect": "锂中毒", "mechanism": "锂清除减少", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "ARB类", "severity": "moderate", "effect": "锂中毒", "mechanism": "锂清除减少", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "布洛芬", "severity": "moderate", "effect": "锂中毒", "mechanism": "锂清除减少", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "双氯芬酸钠", "severity": "moderate", "effect": "锂中毒", "mechanism": "锂清除减少", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "吲哚美辛", "severity": "moderate", "effect": "锂中毒", "mechanism": "锂清除减少", "management": "监测锂浓度"},

            # Lithium continued
            {"drug_1": "锂剂", "drug_2": "卡马西平", "severity": "moderate", "effect": "神经毒性增加", "mechanism": "协同神经毒性", "management": "监测神经系统症状"},
            {"drug_1": "锂剂", "drug_2": "氟西汀", "severity": "moderate", "effect": "锂浓度升高", "mechanism": "未知", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "舍曲林", "severity": "moderate", "effect": "锂浓度可能升高", "mechanism": "未知", "management": "监测锂浓度"},
            {"drug_1": "锂剂", "drug_2": "茶碱", "severity": "moderate", "effect": "锂清除增加", "mechanism": "肾排泄增加", "management": "监测锂浓度"},

            # Antiepileptic drug interactions
            {"drug_1": "丙戊酸钠", "drug_2": "阿司匹林", "severity": "moderate", "effect": "丙戊酸蛋白结合增加", "mechanism": "蛋白置换", "management": "监测丙戊酸浓度"},
            {"drug_1": "丙戊酸钠", "drug_2": "苯妥英钠", "severity": "moderate", "effect": "相互浓度变化", "mechanism": "复杂相互作用", "management": "监测两者浓度"},
            {"drug_1": "丙戊酸钠", "drug_2": "卡马西平", "severity": "moderate", "effect": "丙戊酸浓度降低", "mechanism": "酶诱导", "management": "监测丙戊酸浓度"},
            {"drug_1": "丙戊酸钠", "drug_2": "苯巴比妥", "severity": "moderate", "effect": "丙戊酸浓度降低", "mechanism": "酶诱导", "management": "监测丙戊酸浓度"},
            {"drug_1": "丙戊酸钠", "drug_2": "拉莫三嗪", "severity": "moderate", "effect": "拉莫三嗪浓度升高、皮疹风险", "mechanism": "代谢抑制", "management": "减慢加量"},
            {"drug_1": "丙戊酸钠", "drug_2": "乙酰唑胺", "severity": "moderate", "effect": "代谢性酸中毒风险", "mechanism": "协同酸中毒", "management": "监测血气"},
            {"drug_1": "卡马西平", "drug_2": "红霉素", "severity": "moderate", "effect": "卡马西平中毒", "mechanism": "CYP3A4抑制", "management": "监测卡马西平浓度"},
            {"drug_1": "卡马西平", "drug_2": "克拉霉素", "severity": "critical", "effect": "卡马西平中毒", "mechanism": "CYP3A4抑制", "management": "避免联用"},
            {"drug_1": "卡马西平", "drug_2": "酮康唑", "severity": "critical", "effect": "卡马西平中毒", "mechanism": "CYP3A4抑制", "management": "避免联用"},
            {"drug_1": "卡马西平", "drug_2": "伊曲康唑", "severity": "critical", "effect": "卡马西平中毒", "mechanism": "CYP3A4抑制", "management": "避免联用"},
            {"drug_1": "卡马西平", "drug_2": "氟西汀", "severity": "moderate", "effect": "卡马西平浓度升高", "mechanism": "CYP抑制", "management": "监测卡马西平浓度"},
            {"drug_1": "卡马西平", "drug_2": "华法林", "severity": "moderate", "effect": "华法林疗效降低", "mechanism": "酶诱导", "management": "增加华法林剂量"},
            {"drug_1": "卡马西平", "drug_2": "多西环素", "severity": "moderate", "effect": "多西环素疗效降低", "mechanism": "酶诱导", "management": "考虑增加剂量"},
            {"drug_1": "卡马西平", "drug_2": "左炔诺孕酮", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "卡马西平", "drug_2": "喹硫平", "severity": "moderate", "effect": "喹硫平浓度降低", "mechanism": "CYP3A4诱导", "management": "增加喹硫平剂量"},
            {"drug_1": "卡马西平", "drug_2": "奥氮平", "severity": "moderate", "effect": "奥氮平浓度降低", "mechanism": "CYP1A2诱导", "management": "监测疗效"},
            {"drug_1": "卡马西平", "drug_2": "氯氮平", "severity": "moderate", "effect": "氯氮平浓度降低", "mechanism": "酶诱导", "management": "监测疗效"},
            {"drug_1": "卡马西平", "drug_2": "拉莫三嗪", "severity": "moderate", "effect": "拉莫三嗪浓度降低", "mechanism": "酶诱导", "management": "调整拉莫三嗪剂量"},
            {"drug_1": "卡马西平", "drug_2": "托吡酯", "severity": "moderate", "effect": "卡马西平浓度降低", "mechanism": "相互影响", "management": "监测两者浓度"},
            {"drug_1": "卡马西平", "drug_2": "唑尼沙胺", "severity": "moderate", "effect": "卡马西平浓度降低", "mechanism": "酶诱导", "management": "监测浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "华法林", "severity": "moderate", "effect": "华法林疗效降低", "mechanism": "酶诱导", "management": "增加华法林剂量"},
            {"drug_1": "苯妥英钠", "drug_2": "氟康唑", "severity": "moderate", "effect": "苯妥英浓度升高", "mechanism": "CYP抑制", "management": "监测苯妥英浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "酮康唑", "severity": "moderate", "effect": "苯妥英浓度升高", "mechanism": "CYP抑制", "management": "监测苯妥英浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "伊曲康唑", "severity": "moderate", "effect": "相互浓度降低", "mechanism": "CYP诱导", "management": "避免联用"},
            {"drug_1": "苯妥英钠", "drug_2": "西咪替丁", "severity": "moderate", "effect": "苯妥英浓度升高", "mechanism": "CYP抑制", "management": "监测苯妥英浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "奥美拉唑", "severity": "moderate", "effect": "苯妥英浓度升高", "mechanism": "CYP抑制", "management": "监测苯妥英浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "多西环素", "severity": "moderate", "effect": "多西环素疗效降低", "mechanism": "酶诱导", "management": "考虑增加剂量"},
            {"drug_1": "苯妥英钠", "drug_2": "左炔诺孕酮", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "苯妥英钠", "drug_2": "奎尼丁", "severity": "moderate", "effect": "奎尼丁浓度降低", "mechanism": "酶诱导", "management": "监测奎尼丁浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "美西律", "severity": "moderate", "effect": "美西律浓度降低", "mechanism": "酶诱导", "management": "监测美西律浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "氟哌啶醇", "severity": "moderate", "effect": "氟哌啶醇浓度降低", "mechanism": "酶诱导", "management": "监测疗效"},
            {"drug_1": "苯妥英钠", "drug_2": "氯丙嗪", "severity": "moderate", "effect": "氯丙嗪浓度降低", "mechanism": "酶诱导", "management": "监测疗效"},
            {"drug_1": "苯妥英钠", "drug_2": "氯氮平", "severity": "moderate", "effect": "氯氮平浓度降低", "mechanism": "酶诱导", "management": "监测疗效"},
            {"drug_1": "苯妥英钠", "drug_2": "多奈哌齐", "severity": "moderate", "effect": "多奈哌齐疗效降低", "mechanism": "酶诱导", "management": "监测疗效"},
            {"drug_1": "苯妥英钠", "drug_2": "他克莫司", "severity": "moderate", "effect": "他克莫司浓度降低", "mechanism": "酶诱导", "management": "监测他克莫司浓度"},
            {"drug_1": "苯妥英钠", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度降低", "mechanism": "酶诱导", "management": "监测环孢素浓度"},
            {"drug_1": "苯巴比妥", "drug_2": "华法林", "severity": "moderate", "effect": "华法林疗效降低", "mechanism": "酶诱导", "management": "增加华法林剂量"},
            {"drug_1": "苯巴比妥", "drug_2": "多西环素", "severity": "moderate", "effect": "多西环素疗效降低", "mechanism": "酶诱导", "management": "考虑增加剂量"},
            {"drug_1": "苯巴比妥", "drug_2": "左炔诺孕酮", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "苯巴比妥", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度降低", "mechanism": "酶诱导", "management": "监测环孢素浓度"},
            {"drug_1": "苯巴比妥", "drug_2": "他克莫司", "severity": "moderate", "effect": "他克莫司浓度降低", "mechanism": "酶诱导", "management": "监测他克莫司浓度"},
            {"drug_1": "扑米酮", "drug_2": "华法林", "severity": "moderate", "effect": "华法林疗效降低", "mechanism": "酶诱导", "management": "监测INR"},
            {"drug_1": "拉莫三嗪", "drug_2": "丙戊酸钠", "severity": "moderate", "effect": "拉莫三嗪浓度升高、皮疹风险", "mechanism": "代谢抑制", "management": "减慢加量"},
            {"drug_1": "拉莫三嗪", "drug_2": "卡马西平", "severity": "moderate", "effect": "拉莫三嗪浓度降低", "mechanism": "酶诱导", "management": "调整剂量"},
            {"drug_1": "托吡酯", "drug_2": "丙戊酸钠", "severity": "moderate", "effect": "丙戊酸浓度可能降低", "mechanism": "未知", "management": "监测浓度"},
            {"drug_1": "托吡酯", "drug_2": "苯妥英钠", "severity": "moderate", "effect": "托吡酯浓度可能降低", "mechanism": "酶诱导", "management": "监测浓度"},
            {"drug_1": "左乙拉西坦", "drug_2": "卡马西平", "severity": "mild", "effect": "无显著相互作用", "mechanism": "无", "management": "一般无需调整"},
            {"drug_1": "加巴喷丁", "drug_2": "氢氧化铝", "severity": "moderate", "effect": "加巴喷丁吸收减少", "mechanism": "吸附", "management": "间隔2小时服用"},
            {"drug_1": "加巴喷丁", "drug_2": "吗啡", "severity": "moderate", "effect": "加巴喷丁浓度升高", "mechanism": "吸收增加", "management": "监测镇静作用"},
            {"drug_1": "普瑞巴林", "drug_2": "氢氧化铝", "severity": "moderate", "effect": "普瑞巴林吸收减少", "mechanism": "吸附", "management": "间隔服用"},

            # Ophthalmic interactions
            {"drug_1": "噻摩洛尔", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "β阻滞作用增强", "mechanism": "协同作用", "management": "监测心率和血压"},
            {"drug_1": "噻摩洛尔", "drug_2": "维拉帕米", "severity": "moderate", "effect": "心动过缓、房室传导阻滞", "mechanism": "协同抑制", "management": "避免联用"},
            {"drug_1": "毛果芸香碱", "drug_2": "β阻滞剂", "severity": "moderate", "effect": "瞳孔缩小", "mechanism": "协同缩瞳", "management": "监测眼压"},

            # Other additional interactions
            {"drug_1": "秋水仙碱", "drug_2": "克拉霉素", "severity": "critical", "effect": "秋水仙碱中毒", "mechanism": "CYP3A4/P-gp抑制", "management": "禁用或减量90%"},
            {"drug_1": "秋水仙碱", "drug_2": "酮康唑", "severity": "critical", "effect": "秋水仙碱中毒", "mechanism": "CYP3A4/P-gp抑制", "management": "禁用或减量90%"},
            {"drug_1": "秋水仙碱", "drug_2": "环孢素", "severity": "critical", "effect": "秋水仙碱中毒", "mechanism": "P-gp抑制", "management": "禁用或减量75%"},
            {"drug_1": "秋水仙碱", "drug_2": "维拉帕米", "severity": "moderate", "effect": "秋水仙碱毒性增加", "mechanism": "P-gp抑制", "management": "减少剂量"},
            {"drug_1": "别嘌醇", "drug_2": "硫唑嘌呤", "severity": "critical", "effect": "骨髓抑制", "mechanism": "黄嘌呤氧化酶抑制", "management": "减量75%"},
            {"drug_1": "别嘌醇", "drug_2": "巯嘌呤", "severity": "critical", "effect": "骨髓抑制", "mechanism": "黄嘌呤氧化酶抑制", "management": "减量75%"},
            {"drug_1": "别嘌醇", "drug_2": "华法林", "severity": "moderate", "effect": "INR升高", "mechanism": "未知", "management": "监测INR"},
            {"drug_1": "苯溴马隆", "drug_2": "阿司匹林", "severity": "mild", "effect": "疗效可能降低", "mechanism": "竞争尿酸排泄", "management": "监测尿酸"},
            {"drug_1": "苯溴马隆", "drug_2": "水杨酸盐", "severity": "mild", "effect": "疗效可能降低", "mechanism": "竞争尿酸排泄", "management": "监测尿酸"},

            # Myasthenia gravis drug interactions
            {"drug_1": "溴吡斯的明", "drug_2": "阿托品", "severity": "moderate", "effect": "疗效降低", "mechanism": "药理拮抗", "management": "调整剂量"},
            {"drug_1": "溴吡斯的明", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "肌无力加重", "mechanism": "神经肌肉阻滞", "management": "避免联用"},
            {"drug_1": "溴吡斯的明", "drug_2": "氨基糖苷类", "severity": "moderate", "effect": "肌无力加重", "mechanism": "神经肌肉阻滞", "management": "避免联用"},
            {"drug_1": "溴吡斯的明", "drug_2": "氟喹诺酮类", "severity": "moderate", "effect": "肌无力加重", "mechanism": "神经肌肉阻滞", "management": "谨慎使用"},
            {"drug_1": "溴吡斯的明", "drug_2": "大环内酯类", "severity": "moderate", "effect": "肌无力加重", "mechanism": "神经肌肉阻滞", "management": "谨慎使用"},
            {"drug_1": "溴吡斯的明", "drug_2": "奎宁", "severity": "moderate", "effect": "肌无力加重", "mechanism": "神经肌肉阻滞", "management": "避免联用"},
            {"drug_1": "溴吡斯的明", "drug_2": "奎尼丁", "severity": "moderate", "effect": "肌无力加重", "mechanism": "神经肌肉阻滞", "management": "避免联用"},

            # Parkinson's disease interactions
            {"drug_1": "左旋多巴", "drug_2": "维生素B6", "severity": "moderate", "effect": "左旋多巴疗效降低", "mechanism": "外周脱羧", "management": "使用卡比多巴-左旋多巴"},
            {"drug_1": "左旋多巴", "drug_2": "吡哆醇", "severity": "moderate", "effect": "左旋多巴疗效降低", "mechanism": "外周脱羧", "management": "使用卡比多巴-左旋多巴"},
            {"drug_1": "左旋多巴", "drug_2": "苯妥英钠", "severity": "moderate", "effect": "左旋多巴疗效降低", "mechanism": "未知", "management": "监测疗效"},
            {"drug_1": "左旋多巴", "drug_2": "普萘洛尔", "severity": "mild", "effect": "疗效可能降低", "mechanism": "未知", "management": "监测疗效"},
            {"drug_1": "左旋多巴", "drug_2": "MAO-B抑制剂", "severity": "critical", "effect": "高血压危象", "mechanism": "儿茶酚胺蓄积", "management": "禁用非选择性MAOI"},
            {"drug_1": "司来吉兰", "drug_2": "左旋多巴", "severity": "mild", "effect": "运动障碍", "mechanism": "多巴胺增加", "management": "减少左旋多巴剂量"},
            {"drug_1": "司来吉兰", "drug_2": "哌替啶", "severity": "critical", "effect": "5-羟色胺综合征", "mechanism": "5-HT蓄积", "management": "禁用"},
            {"drug_1": "恩他卡朋", "drug_2": "铁剂", "severity": "moderate", "effect": "恩他卡朋吸收减少", "mechanism": "螯合", "management": "间隔服用"},
            {"drug_1": "金刚烷胺", "drug_2": "金刚乙胺", "severity": "moderate", "effect": "两者毒性增加", "mechanism": "协同作用", "management": "避免联用"},
            {"drug_1": "金刚烷胺", "drug_2": "抗胆碱药", "severity": "moderate", "effect": "抗胆碱作用增强", "mechanism": "协同作用", "management": "监测不良反应"},
            {"drug_1": "金刚烷胺", "drug_2": "利尿剂", "severity": "mild", "effect": "金刚烷胺清除减少", "mechanism": "肾功能影响", "management": "监测不良反应"},
            {"drug_1": "苯海索", "drug_2": "抗胆碱药", "severity": "moderate", "effect": "抗胆碱作用增强", "mechanism": "协同作用", "management": "监测不良反应"},
            {"drug_1": "苯海索", "drug_2": "普萘洛尔", "severity": "moderate", "effect": "记忆障碍", "mechanism": "未知", "management": "监测认知功能"},

            # Alzheimer's drug interactions
            {"drug_1": "多奈哌齐", "drug_2": "琥珀酰胆碱", "severity": "moderate", "effect": "神经肌肉阻滞延长", "mechanism": "胆碱酯酶抑制", "management": "谨慎使用"},
            {"drug_1": "多奈哌齐", "drug_2": "β阻滞剂", "severity": "mild", "effect": "心动过缓", "mechanism": "心动过缓风险", "management": "监测心率"},
            {"drug_1": "多奈哌齐", "drug_2": "卡马西平", "severity": "moderate", "effect": "多奈哌齐疗效降低", "mechanism": "酶诱导", "management": "监测疗效"},
            {"drug_1": "卡巴拉汀", "drug_2": "琥珀酰胆碱", "severity": "moderate", "effect": "神经肌肉阻滞延长", "mechanism": "胆碱酯酶抑制", "management": "谨慎使用"},
            {"drug_1": "美金刚", "drug_2": "右美沙芬", "severity": "moderate", "effect": "精神病性症状", "mechanism": "NMDA拮抗协同", "management": "避免联用"},

            # Anti-obesity drug interactions
            {"drug_1": "奥利司他", "drug_2": "脂溶性维生素", "severity": "mild", "effect": "维生素吸收减少", "mechanism": "脂肪吸收减少", "management": "补充维生素"},
            {"drug_1": "奥利司他", "drug_2": "左甲状腺素", "severity": "moderate", "effect": "甲状腺素吸收减少", "mechanism": "吸收减少", "management": "间隔4小时服用"},
            {"drug_1": "奥利司他", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素吸收减少", "mechanism": "吸收减少", "management": "间隔服用并监测"},
            {"drug_1": "奥利司他", "drug_2": "华法林", "severity": "moderate", "effect": "INR变化", "mechanism": "维生素K吸收减少", "management": "监测INR"},
            {"drug_1": "利拉鲁肽", "drug_2": "胰岛素", "severity": "moderate", "effect": "低血糖", "mechanism": "协同降糖", "management": "减少胰岛素剂量"},
            {"drug_1": "利拉鲁肽", "drug_2": "磺酰脲类", "severity": "moderate", "effect": "低血糖", "mechanism": "协同降糖", "management": "减少磺酰脲剂量"},
            {"drug_1": "司美格鲁肽", "drug_2": "胰岛素", "severity": "moderate", "effect": "低血糖", "mechanism": "协同降糖", "management": "减少胰岛素剂量"},
            {"drug_1": "司美格鲁肽", "drug_2": "磺酰脲类", "severity": "moderate", "effect": "低血糖", "mechanism": "协同降糖", "management": "减少磺酰脲剂量"},
            {"drug_1": "芬特明", "drug_2": "MAOI", "severity": "critical", "effect": "高血压危象", "mechanism": "儿茶酚胺蓄积", "management": "禁用"},
            {"drug_1": "芬特明", "drug_2": "氟西汀", "severity": "moderate", "effect": "5-羟色胺综合征风险", "mechanism": "5-HT效应", "management": "谨慎联用"},

            # Additional gynecology/hormonal interactions
            {"drug_1": "雌激素", "drug_2": "华法林", "severity": "moderate", "effect": "抗凝效果降低", "mechanism": "凝血因子合成增加", "management": "监测INR"},
            {"drug_1": "雌激素", "drug_2": "拉莫三嗪", "severity": "moderate", "effect": "拉莫三嗪浓度降低", "mechanism": "葡萄糖醛酸化诱导", "management": "监测拉莫三嗪浓度"},
            {"drug_1": "孕激素", "drug_2": "拉莫三嗪", "severity": "mild", "effect": "拉莫三嗪浓度变化", "mechanism": "葡萄糖醛酸化影响", "management": "监测疗效"},
            {"drug_1": "口服避孕药", "drug_2": "利福平", "severity": "critical", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "苯妥英钠", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "卡马西平", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "苯巴比妥", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "扑米酮", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "托吡酯", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "奥卡西平", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "灰黄霉素", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "莫达非尼", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "博舒替尼", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "依曲韦林", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},
            {"drug_1": "口服避孕药", "drug_2": "奈韦拉平", "severity": "moderate", "effect": "避孕失败", "mechanism": "酶诱导", "management": "加用屏障避孕"},

            # Misc interactions
            {"drug_1": "甲氨蝶呤", "drug_2": "阿司匹林", "severity": "moderate", "effect": "甲氨蝶呤毒性增加", "mechanism": "肾清除减少", "management": "监测甲氨蝶呤浓度"},
            {"drug_1": "甲氨蝶呤", "drug_2": "NSAIDs", "severity": "moderate", "effect": "甲氨蝶呤毒性增加", "mechanism": "肾清除减少", "management": "监测甲氨蝶呤浓度"},
            {"drug_1": "甲氨蝶呤", "drug_2": "丙磺舒", "severity": "moderate", "effect": "甲氨蝶呤毒性增加", "mechanism": "肾排泄抑制", "management": "减少甲氨蝶呤剂量"},
            {"drug_1": "甲氨蝶呤", "drug_2": "复方磺胺甲噁唑", "severity": "critical", "effect": "骨髓抑制", "mechanism": "协同叶酸拮抗", "management": "禁用或谨慎使用"},
            {"drug_1": "来氟米特", "drug_2": "甲氨蝶呤", "severity": "moderate", "effect": "肝毒性增加", "mechanism": "协同肝毒性", "management": "监测肝功能"},
            {"drug_1": "来氟米特", "drug_2": "华法林", "severity": "moderate", "effect": "INR升高", "mechanism": "蛋白结合置换", "management": "监测INR"},
            {"drug_1": "羟氯喹", "drug_2": "地高辛", "severity": "moderate", "effect": "地高辛浓度升高", "mechanism": "P-gp抑制", "management": "监测地高辛"},
            {"drug_1": "羟氯喹", "drug_2": "环孢素", "severity": "moderate", "effect": "环孢素浓度升高", "mechanism": "P-gp抑制", "management": "监测环孢素"},
            {"drug_1": "柳氮磺吡啶", "drug_2": "华法林", "severity": "moderate", "effect": "抗凝效果增强", "mechanism": "未知", "management": "监测INR"},
            {"drug_1": "金制剂", "drug_2": "青霉胺", "severity": "moderate", "effect": "血液/肾毒性增加", "mechanism": "协同毒性", "management": "避免联用"},
        ],
        "mild": [
            {"drug_1": "奥美拉唑", "drug_2": "地高辛", "severity": "mild", "effect": "地高辛吸收增加", "mechanism": "胃酸减少", "management": "监测地高辛"},
            {"drug_1": "奥美拉唑", "drug_2": "铁剂", "severity": "mild", "effect": "铁剂吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "奥美拉唑", "drug_2": "维生素B12", "severity": "mild", "effect": "B12吸收减少", "mechanism": "酸分泌减少", "management": "长期使用监测B12"},
            {"drug_1": "奥美拉唑", "drug_2": "酮康唑", "severity": "mild", "effect": "酮康唑吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "奥美拉唑", "drug_2": "伊曲康唑", "severity": "mild", "effect": "伊曲康唑吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "奥美拉唑", "drug_2": "泼尼松", "severity": "mild", "effect": "泼尼松吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "兰索拉唑", "drug_2": "地高辛", "severity": "mild", "effect": "地高辛吸收变化", "mechanism": "胃酸减少", "management": "监测地高辛"},
            {"drug_1": "兰索拉唑", "drug_2": "酮康唑", "severity": "mild", "effect": "酮康唑吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "兰索拉唑", "drug_2": "铁剂", "severity": "mild", "effect": "铁剂吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "泮托拉唑", "drug_2": "地高辛", "severity": "mild", "effect": "地高辛吸收减少", "mechanism": "胃酸减少", "management": "监测地高辛"},
            {"drug_1": "泮托拉唑", "drug_2": "酮康唑", "severity": "mild", "effect": "酮康唑吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "雷贝拉唑", "drug_2": "地高辛", "severity": "mild", "effect": "地高辛吸收变化", "mechanism": "胃酸减少", "management": "监测地高辛"},
            {"drug_1": "雷贝拉唑", "drug_2": "酮康唑", "severity": "mild", "effect": "酮康唑吸收减少", "mechanism": "胃酸减少", "management": "分开服用"},
            {"drug_1": "法莫替丁", "drug_2": "抗酸药", "severity": "mild", "effect": "法莫替丁吸收减少", "mechanism": "胃内结合", "management": "间隔2小时"},
            {"drug_1": "西咪替丁", "drug_2": "抗酸药", "severity": "mild", "effect": "西咪替丁吸收减少", "mechanism": "胃内结合", "management": "间隔1小时"},
            {"drug_1": "西咪替丁", "drug_2": "美托洛尔", "severity": "mild", "effect": "β阻滞剂浓度升高", "mechanism": "肝血流减少", "management": "监测心率"},
            {"drug_1": "西咪替丁", "drug_2": "普萘洛尔", "severity": "mild", "effect": "普萘洛尔浓度升高", "mechanism": "肝血流减少", "management": "监测心率"},
            {"drug_1": "西咪替丁", "drug_2": "美西律", "severity": "mild", "effect": "美西律浓度升高", "mechanism": "CYP2D6抑制", "management": "监测心电图"},
            {"drug_1": "西咪替丁", "drug_2": "奎尼丁", "severity": "mild", "effect": "奎尼丁浓度升高", "mechanism": "CYP抑制", "management": "监测奎尼丁"},
            {"drug_1": "西咪替丁", "drug_2": "利多卡因", "severity": "mild", "effect": "利多卡因浓度升高", "mechanism": "肝血流减少", "management": "监测利多卡因"},
            {"drug_1": "西咪替丁", "drug_2": "苯妥英钠", "severity": "mild", "effect": "苯妥英浓度升高", "mechanism": "CYP抑制", "management": "监测苯妥英"},
            {"drug_1": "西咪替丁", "drug_2": "卡马西平", "severity": "mild", "effect": "卡马西平浓度升高", "mechanism": "CYP抑制", "management": "监测卡马西平"},
            {"drug_1": "西咪替丁", "drug_2": "华法林", "severity": "mild", "effect": "INR升高", "mechanism": "CYP抑制", "management": "监测INR"},
            {"drug_1": "西咪替丁", "drug_2": "茶碱", "severity": "mild", "effect": "茶碱浓度升高", "mechanism": "CYP抑制", "management": "监测茶碱"},
            {"drug_1": "西咪替丁", "drug_2": "咖啡因", "severity": "mild", "effect": "咖啡因浓度升高", "mechanism": "CYP1A2抑制", "management": "一般无需处理"},
            {"drug_1": "西咪替丁", "drug_2": "美沙酮", "severity": "mild", "effect": "美沙酮浓度升高", "mechanism": "CYP抑制", "management": "监测美沙酮"},
            {"drug_1": "西咪替丁", "drug_2": "普罗帕酮", "severity": "mild", "effect": "普罗帕酮浓度升高", "mechanism": "CYP抑制", "management": "监测心电图"},
            {"drug_1": "西咪替丁", "drug_2": "氟卡尼", "severity": "mild", "effect": "氟卡尼浓度升高", "mechanism": "CYP抑制", "management": "监测心电图"},
            {"drug_1": "西咪替丁", "drug_2": "β受体阻滞剂", "severity": "mild", "effect": "β阻滞剂浓度升高", "mechanism": "肝血流减少", "management": "监测心率血压"},
            {"drug_1": "西咪替丁", "drug_2": "钙通道阻滞剂", "severity": "mild", "effect": "CCB浓度升高", "mechanism": "CYP抑制", "management": "监测血压"},
            {"drug_1": "西咪替丁", "drug_2": "他克莫司", "severity": "mild", "effect": "他克莫司浓度升高", "mechanism": "CYP抑制", "management": "监测他克莫司"},
            {"drug_1": "西咪替丁", "drug_2": "环孢素", "severity": "mild", "effect": "环孢素浓度升高", "mechanism": "CYP抑制", "management": "监测环孢素"},
            {"drug_1": "雷尼替丁", "drug_2": "普萘洛尔", "severity": "mild", "effect": "普萘洛尔浓度升高", "mechanism": "代谢抑制", "management": "监测心率"},
            {"drug_1": "雷尼替丁", "drug_2": "美托洛尔", "severity": "mild", "effect": "美托洛尔浓度轻度升高", "mechanism": "代谢抑制", "management": "监测心率"},
            {"drug_1": "雷尼替丁", "drug_2": "阿替洛尔", "severity": "mild", "effect": "阿替洛尔浓度升高", "mechanism": "肾排泄减少", "management": "监测心率"},
            {"drug_1": "雷尼替丁", "drug_2": "纳多洛尔", "severity": "mild", "effect": "纳多洛尔浓度升高", "mechanism": "肾排泄减少", "management": "监测心率"},
            {"drug_1": "雷尼替丁", "drug_2": "抗酸药", "severity": "mild", "effect": "雷尼替丁吸收减少", "mechanism": "胃内结合", "management": "间隔2小时"},
        ]
    }
    return additional_interactions
